### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by gabriead** [gereleth/jupyter-bbox-widget#6]
Hi Gereleth,
love your annotation tool but running into problems running the widget on my jupyterlab. I can render other ipywidgets in my jupterlab without any problems.
Packages currently installed:
Selected Jupyter core packages...
```
IPython          : 7.29.0
ipykernel        : 6.5.0
ipywidgets       : 7.6.5
jupyter_client   : 7.0.6
jupyter_core     : 4.9.1
jupyter_server   : 1.11.2
jupyterlab       : 3.2.2
nbclient         : 0.5.5
nbconvert        : 6.2.0
nbformat         : 5.1.3
notebook         : 6.4.5
qtconsole        : not installed
traitlets        : 5.1.1
```
Running this snippet:

![Unbenannt](https://user-images.githubusercontent.com/9105222/141082183-67141260-8765-485d-a319-9786f7f2b6b1.PNG)

Error:
`Error displaying widget: model not found`

Any hints on what might cause the problem?

**Comment by gereleth** [comment]
Hi Gabriead,

I'm not sure what is causing this issue. The widget doesn't work in `jupyter lab` on Binder either. But it works when using classic `jupyter notebook`. Could you try that as a workaround?

I'll try to look into this later.

**Comment by gabriead** [comment]
Hi Gereleth, if I am using 'Jupyter Notebook' then the image to be annotated does not get rendered
![Unbenannt](https://user-images.githubusercontent.com/9105222/141274135-fc30d642-a530-4d48-a8de-d6250c14e5e4.PNG)
.

**Comment by gereleth** [comment]
I saw the same error in my jupyter lab installation. But when I create a fresh virtual environment with `jupyterlab` and `jupyter_bbox_widget` then the widget shows up fine.

So in the env with this error I ran `jupyter labextension list`. It showed the following output:

```
JupyterLab v3.2.4
/home/daria/uchipy/share/jupyter/labextensions
        ipycanvas v0.8.2 enabled OK
        jupyterlab-plotly v5.2.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /home/daria/uchipy/share/jupyter/lab
        jupyter-bbox-widget v0.3.3 enabled OK
        jupyter-matplotlib v0.4.2 enabled OK
```

And since the `jupyter-matplotlib` was right next to the widget I tried uninstalling it with `jupyter labextension uninstall jupyter-matplotlib`. After this the widget started working again. So there must have been some extension conflict.

In order to still have access to interactive plots I ran `pip install --upgrade ipympl` followed by `jupyter lab build` (just in case). And now I can use both the `jupyter_bbox_widget` and the interactive matplotlib plots.

So I guess this issue is related to a specific installation. The steps I'd suggest are:

- try installing jupyterlab and the widget into a fresh environment to see if it works then
- look into other labextensions that you have installed, try removing/upgrading/reinstalling them
